version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: backend:latest
    build:
      context: ./backend/migrations
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    environment:
      AUTH_SERVICE_GRPC_PORT: 50051
      ESSAY_SERVICE_GRPC_PORT: 50052
      REVIEW_SERVICE_GRPC_PORT: 50053
      NOTIFICATIONS_SERVICE_GRPC_PORT: 50054
    depends_on:
      auth-service:
        condition: service_started
      essay-service:
        condition: service_started
      review-service:
        condition: service_started
      notification-service:
        condition: service_started
    networks:
      - app-network
    ports:
      - "8080:8080"

  auth-service:
    build:
      context: ./backend
      dockerfile: auth-service/Dockerfile
    environment:
      AUTH_SERVICE_GRPC_PORT: 50051
    env_file: .env # JWT and postgres secrets
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - app-network

  essay-service:
    build:
      context: ./backend
      dockerfile: essay-service/Dockerfile
    environment:
      ESSAY_SERVICE_GRPC_PORT: 50052
      REVIEW_SERVICE_GRPC_PORT: 50053
    env_file: .env # postgres secrets
    depends_on:
      migrations:
        condition: service_completed_successfully
      review-service:
        condition: service_started
    networks:
      - app-network

  review-service:
    build:
      context: ./backend
      dockerfile: review-service/Dockerfile
    environment:
      REVIEW_SERVICE_GRPC_PORT: 50053
      KAFKA_BROKERS: kafka:9092
    env_file: .env # postgres secrets
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - app-network

  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/Dockerfile
    environment:
      NOTIFICATIONS_SERVICE_GRPC_PORT: 50054
      KAFKA_BROKERS: kafka:9092
    env_file: .env # postgres secrets
    depends_on:
      migrations:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9092:9092"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
