// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: essay/essay.proto

package essay

import (
	review "github.com/IAGrig/vt-csa-essays/backend/proto/review"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EssayAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EssayAddRequest) Reset() {
	*x = EssayAddRequest{}
	mi := &file_essay_essay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EssayAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EssayAddRequest) ProtoMessage() {}

func (x *EssayAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EssayAddRequest.ProtoReflect.Descriptor instead.
func (*EssayAddRequest) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{0}
}

func (x *EssayAddRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EssayAddRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type EssayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EssayResponse) Reset() {
	*x = EssayResponse{}
	mi := &file_essay_essay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EssayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EssayResponse) ProtoMessage() {}

func (x *EssayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EssayResponse.ProtoReflect.Descriptor instead.
func (*EssayResponse) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{1}
}

func (x *EssayResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EssayResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EssayResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *EssayResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_essay_essay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{2}
}

type GetByAuthorNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorname    string                 `protobuf:"bytes,1,opt,name=authorname,proto3" json:"authorname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByAuthorNameRequest) Reset() {
	*x = GetByAuthorNameRequest{}
	mi := &file_essay_essay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByAuthorNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAuthorNameRequest) ProtoMessage() {}

func (x *GetByAuthorNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAuthorNameRequest.ProtoReflect.Descriptor instead.
func (*GetByAuthorNameRequest) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{3}
}

func (x *GetByAuthorNameRequest) GetAuthorname() string {
	if x != nil {
		return x.Authorname
	}
	return ""
}

type EssayWithReviewsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	AuthorId      int32                    `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     int64                    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Reviews       []*review.ReviewResponse `protobuf:"bytes,6,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EssayWithReviewsResponse) Reset() {
	*x = EssayWithReviewsResponse{}
	mi := &file_essay_essay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EssayWithReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EssayWithReviewsResponse) ProtoMessage() {}

func (x *EssayWithReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EssayWithReviewsResponse.ProtoReflect.Descriptor instead.
func (*EssayWithReviewsResponse) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{4}
}

func (x *EssayWithReviewsResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EssayWithReviewsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EssayWithReviewsResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *EssayWithReviewsResponse) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *EssayWithReviewsResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EssayWithReviewsResponse) GetReviews() []*review.ReviewResponse {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type RemoveByAuthorNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorname    string                 `protobuf:"bytes,1,opt,name=authorname,proto3" json:"authorname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveByAuthorNameRequest) Reset() {
	*x = RemoveByAuthorNameRequest{}
	mi := &file_essay_essay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveByAuthorNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveByAuthorNameRequest) ProtoMessage() {}

func (x *RemoveByAuthorNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveByAuthorNameRequest.ProtoReflect.Descriptor instead.
func (*RemoveByAuthorNameRequest) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveByAuthorNameRequest) GetAuthorname() string {
	if x != nil {
		return x.Authorname
	}
	return ""
}

type SearchByContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByContentRequest) Reset() {
	*x = SearchByContentRequest{}
	mi := &file_essay_essay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByContentRequest) ProtoMessage() {}

func (x *SearchByContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_essay_essay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByContentRequest.ProtoReflect.Descriptor instead.
func (*SearchByContentRequest) Descriptor() ([]byte, []int) {
	return file_essay_essay_proto_rawDescGZIP(), []int{6}
}

func (x *SearchByContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_essay_essay_proto protoreflect.FileDescriptor

const file_essay_essay_proto_rawDesc = "" +
	"\n" +
	"\x11essay/essay.proto\x12\x05essay\x1a\x13review/review.proto\"C\n" +
	"\x0fEssayAddRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\"p\n" +
	"\rEssayResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x0e\n" +
	"\fEmptyRequest\"8\n" +
	"\x16GetByAuthorNameRequest\x12\x1e\n" +
	"\n" +
	"authorname\x18\x01 \x01(\tR\n" +
	"authorname\"\xca\x01\n" +
	"\x18EssayWithReviewsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x05R\bauthorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x120\n" +
	"\areviews\x18\x06 \x03(\v2\x16.review.ReviewResponseR\areviews\";\n" +
	"\x19RemoveByAuthorNameRequest\x12\x1e\n" +
	"\n" +
	"authorname\x18\x01 \x01(\tR\n" +
	"authorname\"2\n" +
	"\x16SearchByContentRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2\xf5\x02\n" +
	"\fEssayService\x125\n" +
	"\x03Add\x12\x16.essay.EssayAddRequest\x1a\x14.essay.EssayResponse\"\x00\x12=\n" +
	"\fGetAllEssays\x12\x13.essay.EmptyRequest\x1a\x14.essay.EssayResponse\"\x000\x01\x12S\n" +
	"\x0fGetByAuthorName\x12\x1d.essay.GetByAuthorNameRequest\x1a\x1f.essay.EssayWithReviewsResponse\"\x00\x12N\n" +
	"\x12RemoveByAuthorName\x12 .essay.RemoveByAuthorNameRequest\x1a\x14.essay.EssayResponse\"\x00\x12J\n" +
	"\x0fSearchByContent\x12\x1d.essay.SearchByContentRequest\x1a\x14.essay.EssayResponse\"\x000\x01B5Z3github.com/IAGrig/vt-csa-essays/backend/proto/essayb\x06proto3"

var (
	file_essay_essay_proto_rawDescOnce sync.Once
	file_essay_essay_proto_rawDescData []byte
)

func file_essay_essay_proto_rawDescGZIP() []byte {
	file_essay_essay_proto_rawDescOnce.Do(func() {
		file_essay_essay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_essay_essay_proto_rawDesc), len(file_essay_essay_proto_rawDesc)))
	})
	return file_essay_essay_proto_rawDescData
}

var file_essay_essay_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_essay_essay_proto_goTypes = []any{
	(*EssayAddRequest)(nil),           // 0: essay.EssayAddRequest
	(*EssayResponse)(nil),             // 1: essay.EssayResponse
	(*EmptyRequest)(nil),              // 2: essay.EmptyRequest
	(*GetByAuthorNameRequest)(nil),    // 3: essay.GetByAuthorNameRequest
	(*EssayWithReviewsResponse)(nil),  // 4: essay.EssayWithReviewsResponse
	(*RemoveByAuthorNameRequest)(nil), // 5: essay.RemoveByAuthorNameRequest
	(*SearchByContentRequest)(nil),    // 6: essay.SearchByContentRequest
	(*review.ReviewResponse)(nil),     // 7: review.ReviewResponse
}
var file_essay_essay_proto_depIdxs = []int32{
	7, // 0: essay.EssayWithReviewsResponse.reviews:type_name -> review.ReviewResponse
	0, // 1: essay.EssayService.Add:input_type -> essay.EssayAddRequest
	2, // 2: essay.EssayService.GetAllEssays:input_type -> essay.EmptyRequest
	3, // 3: essay.EssayService.GetByAuthorName:input_type -> essay.GetByAuthorNameRequest
	5, // 4: essay.EssayService.RemoveByAuthorName:input_type -> essay.RemoveByAuthorNameRequest
	6, // 5: essay.EssayService.SearchByContent:input_type -> essay.SearchByContentRequest
	1, // 6: essay.EssayService.Add:output_type -> essay.EssayResponse
	1, // 7: essay.EssayService.GetAllEssays:output_type -> essay.EssayResponse
	4, // 8: essay.EssayService.GetByAuthorName:output_type -> essay.EssayWithReviewsResponse
	1, // 9: essay.EssayService.RemoveByAuthorName:output_type -> essay.EssayResponse
	1, // 10: essay.EssayService.SearchByContent:output_type -> essay.EssayResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_essay_essay_proto_init() }
func file_essay_essay_proto_init() {
	if File_essay_essay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_essay_essay_proto_rawDesc), len(file_essay_essay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_essay_essay_proto_goTypes,
		DependencyIndexes: file_essay_essay_proto_depIdxs,
		MessageInfos:      file_essay_essay_proto_msgTypes,
	}.Build()
	File_essay_essay_proto = out.File
	file_essay_essay_proto_goTypes = nil
	file_essay_essay_proto_depIdxs = nil
}
