// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: review/review.proto

package review

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewService_Add_FullMethodName           = "/review.ReviewService/Add"
	ReviewService_GetAllReviews_FullMethodName = "/review.ReviewService/GetAllReviews"
	ReviewService_GetByEssayId_FullMethodName  = "/review.ReviewService/GetByEssayId"
	ReviewService_RemoveById_FullMethodName    = "/review.ReviewService/RemoveById"
)

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewServiceClient interface {
	Add(ctx context.Context, in *ReviewAddRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	GetAllReviews(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReviewResponse], error)
	GetByEssayId(ctx context.Context, in *GetByEssayIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReviewResponse], error)
	RemoveById(ctx context.Context, in *RemoveByIdRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
}

type reviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewServiceClient(cc grpc.ClientConnInterface) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) Add(ctx context.Context, in *ReviewAddRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, ReviewService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) GetAllReviews(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReviewResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReviewService_ServiceDesc.Streams[0], ReviewService_GetAllReviews_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmptyRequest, ReviewResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReviewService_GetAllReviewsClient = grpc.ServerStreamingClient[ReviewResponse]

func (c *reviewServiceClient) GetByEssayId(ctx context.Context, in *GetByEssayIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReviewResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReviewService_ServiceDesc.Streams[1], ReviewService_GetByEssayId_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetByEssayIdRequest, ReviewResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReviewService_GetByEssayIdClient = grpc.ServerStreamingClient[ReviewResponse]

func (c *reviewServiceClient) RemoveById(ctx context.Context, in *RemoveByIdRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, ReviewService_RemoveById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
// All implementations must embed UnimplementedReviewServiceServer
// for forward compatibility.
type ReviewServiceServer interface {
	Add(context.Context, *ReviewAddRequest) (*ReviewResponse, error)
	GetAllReviews(*EmptyRequest, grpc.ServerStreamingServer[ReviewResponse]) error
	GetByEssayId(*GetByEssayIdRequest, grpc.ServerStreamingServer[ReviewResponse]) error
	RemoveById(context.Context, *RemoveByIdRequest) (*ReviewResponse, error)
	mustEmbedUnimplementedReviewServiceServer()
}

// UnimplementedReviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewServiceServer struct{}

func (UnimplementedReviewServiceServer) Add(context.Context, *ReviewAddRequest) (*ReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedReviewServiceServer) GetAllReviews(*EmptyRequest, grpc.ServerStreamingServer[ReviewResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllReviews not implemented")
}
func (UnimplementedReviewServiceServer) GetByEssayId(*GetByEssayIdRequest, grpc.ServerStreamingServer[ReviewResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetByEssayId not implemented")
}
func (UnimplementedReviewServiceServer) RemoveById(context.Context, *RemoveByIdRequest) (*ReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveById not implemented")
}
func (UnimplementedReviewServiceServer) mustEmbedUnimplementedReviewServiceServer() {}
func (UnimplementedReviewServiceServer) testEmbeddedByValue()                       {}

// UnsafeReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewServiceServer will
// result in compilation errors.
type UnsafeReviewServiceServer interface {
	mustEmbedUnimplementedReviewServiceServer()
}

func RegisterReviewServiceServer(s grpc.ServiceRegistrar, srv ReviewServiceServer) {
	// If the following call pancis, it indicates UnimplementedReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewService_ServiceDesc, srv)
}

func _ReviewService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).Add(ctx, req.(*ReviewAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_GetAllReviews_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReviewServiceServer).GetAllReviews(m, &grpc.GenericServerStream[EmptyRequest, ReviewResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReviewService_GetAllReviewsServer = grpc.ServerStreamingServer[ReviewResponse]

func _ReviewService_GetByEssayId_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetByEssayIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReviewServiceServer).GetByEssayId(m, &grpc.GenericServerStream[GetByEssayIdRequest, ReviewResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReviewService_GetByEssayIdServer = grpc.ServerStreamingServer[ReviewResponse]

func _ReviewService_RemoveById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).RemoveById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewService_RemoveById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).RemoveById(ctx, req.(*RemoveByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewService_ServiceDesc is the grpc.ServiceDesc for ReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "review.ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ReviewService_Add_Handler,
		},
		{
			MethodName: "RemoveById",
			Handler:    _ReviewService_RemoveById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllReviews",
			Handler:       _ReviewService_GetAllReviews_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetByEssayId",
			Handler:       _ReviewService_GetByEssayId_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "review/review.proto",
}
