// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: review/review.proto

package review

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EssayId       int32                  `protobuf:"varint,1,opt,name=essay_id,json=essayId,proto3" json:"essay_id,omitempty"`
	EssayAuthorId int32                  `protobuf:"varint,2,opt,name=essay_author_id,json=essayAuthorId,proto3" json:"essay_author_id,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewAddRequest) Reset() {
	*x = ReviewAddRequest{}
	mi := &file_review_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewAddRequest) ProtoMessage() {}

func (x *ReviewAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewAddRequest.ProtoReflect.Descriptor instead.
func (*ReviewAddRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewAddRequest) GetEssayId() int32 {
	if x != nil {
		return x.EssayId
	}
	return 0
}

func (x *ReviewAddRequest) GetEssayAuthorId() int32 {
	if x != nil {
		return x.EssayAuthorId
	}
	return 0
}

func (x *ReviewAddRequest) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ReviewAddRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewAddRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EssayId       int32                  `protobuf:"varint,2,opt,name=essay_id,json=essayId,proto3" json:"essay_id,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewResponse) GetEssayId() int32 {
	if x != nil {
		return x.EssayId
	}
	return 0
}

func (x *ReviewResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ReviewResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ReviewResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_review_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{2}
}

type GetByEssayIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EssayId       int32                  `protobuf:"varint,1,opt,name=essay_id,json=essayId,proto3" json:"essay_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEssayIdRequest) Reset() {
	*x = GetByEssayIdRequest{}
	mi := &file_review_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEssayIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEssayIdRequest) ProtoMessage() {}

func (x *GetByEssayIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEssayIdRequest.ProtoReflect.Descriptor instead.
func (*GetByEssayIdRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetByEssayIdRequest) GetEssayId() int32 {
	if x != nil {
		return x.EssayId
	}
	return 0
}

type RemoveByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveByIdRequest) Reset() {
	*x = RemoveByIdRequest{}
	mi := &file_review_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveByIdRequest) ProtoMessage() {}

func (x *RemoveByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveByIdRequest.ProtoReflect.Descriptor instead.
func (*RemoveByIdRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_review_review_proto protoreflect.FileDescriptor

const file_review_review_proto_rawDesc = "" +
	"\n" +
	"\x13review/review.proto\x12\x06review\"\x9b\x01\n" +
	"\x10ReviewAddRequest\x12\x19\n" +
	"\bessay_id\x18\x01 \x01(\x05R\aessayId\x12&\n" +
	"\x0fessay_author_id\x18\x02 \x01(\x05R\ressayAuthorId\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\"\xa0\x01\n" +
	"\x0eReviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bessay_id\x18\x02 \x01(\x05R\aessayId\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x0e\n" +
	"\fEmptyRequest\"0\n" +
	"\x13GetByEssayIdRequest\x12\x19\n" +
	"\bessay_id\x18\x01 \x01(\x05R\aessayId\"#\n" +
	"\x11RemoveByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\x99\x02\n" +
	"\rReviewService\x129\n" +
	"\x03Add\x12\x18.review.ReviewAddRequest\x1a\x16.review.ReviewResponse\"\x00\x12A\n" +
	"\rGetAllReviews\x12\x14.review.EmptyRequest\x1a\x16.review.ReviewResponse\"\x000\x01\x12G\n" +
	"\fGetByEssayId\x12\x1b.review.GetByEssayIdRequest\x1a\x16.review.ReviewResponse\"\x000\x01\x12A\n" +
	"\n" +
	"RemoveById\x12\x19.review.RemoveByIdRequest\x1a\x16.review.ReviewResponse\"\x00B6Z4github.com/IAGrig/vt-csa-essays/backend/proto/reviewb\x06proto3"

var (
	file_review_review_proto_rawDescOnce sync.Once
	file_review_review_proto_rawDescData []byte
)

func file_review_review_proto_rawDescGZIP() []byte {
	file_review_review_proto_rawDescOnce.Do(func() {
		file_review_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_review_proto_rawDesc), len(file_review_review_proto_rawDesc)))
	})
	return file_review_review_proto_rawDescData
}

var file_review_review_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_review_review_proto_goTypes = []any{
	(*ReviewAddRequest)(nil),    // 0: review.ReviewAddRequest
	(*ReviewResponse)(nil),      // 1: review.ReviewResponse
	(*EmptyRequest)(nil),        // 2: review.EmptyRequest
	(*GetByEssayIdRequest)(nil), // 3: review.GetByEssayIdRequest
	(*RemoveByIdRequest)(nil),   // 4: review.RemoveByIdRequest
}
var file_review_review_proto_depIdxs = []int32{
	0, // 0: review.ReviewService.Add:input_type -> review.ReviewAddRequest
	2, // 1: review.ReviewService.GetAllReviews:input_type -> review.EmptyRequest
	3, // 2: review.ReviewService.GetByEssayId:input_type -> review.GetByEssayIdRequest
	4, // 3: review.ReviewService.RemoveById:input_type -> review.RemoveByIdRequest
	1, // 4: review.ReviewService.Add:output_type -> review.ReviewResponse
	1, // 5: review.ReviewService.GetAllReviews:output_type -> review.ReviewResponse
	1, // 6: review.ReviewService.GetByEssayId:output_type -> review.ReviewResponse
	1, // 7: review.ReviewService.RemoveById:output_type -> review.ReviewResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_review_review_proto_init() }
func file_review_review_proto_init() {
	if File_review_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_review_proto_rawDesc), len(file_review_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_review_proto_goTypes,
		DependencyIndexes: file_review_review_proto_depIdxs,
		MessageInfos:      file_review_review_proto_msgTypes,
	}.Build()
	File_review_review_proto = out.File
	file_review_review_proto_goTypes = nil
	file_review_review_proto_depIdxs = nil
}
